export interface AuthResponseData {
  id:number,
  nom:string,
  prenom:string,
      civilite: string,
      password: string,
      role: string,
      email: string,
     CIN: string,
        adresse: string,
      telephone: string,
      image: string,
      nom_societe: string,
      patente: number,
      statut_societe: string,
      RC: string,
      type: string,
      old_password: string,
      new_password: string,
      confirm_password: string
  }